Repository hmcts/lau-case-frontend, pull requests merged in 2021-11, with the labels that each got.

#32 LAU-153 Fix Yarn audit issues
  yarn-audit-known-issues
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-case-frontend-pr-32

#31 LAU-150 Fix datepicker font and add CSS for buttons
  src/main/assets/js/flatpickr.ts
  src/main/assets/scss/flatpickr.scss
  src/main/assets/scss/main.scss
  src/main/views/search/template.njk
Labels: ns:lau, prd:lau, rel:lau-case-frontend-pr-31

#33 LAU-143 Pass Authorization header to backend
  src/main/controllers/case-activity.controller.ts
  src/main/controllers/case-searches.controller.ts
  src/main/controllers/search.controller.ts
  src/main/models/appRequest.ts
  src/main/modules/oidc/index.ts
  src/main/service/AuthService.ts
  src/main/service/CaseService.ts
  src/test/unit/controllers/case-activity.test.ts
  src/test/unit/controllers/case-searches.test.ts
  src/test/unit/service/CaseService.test.ts
Labels: ns:lau, prd:lau, rel:lau-case-frontend-pr-33

#34 LAU-147: Replace GDS Fieldset component to fix Firefox.
  bin/generate-ssl-options.sh
  config/development.yaml
  src/main/app.ts
  src/main/modules/session/index.ts
  src/main/views/search/template.njk
Labels: ns:lau, prd:lau, rel:lau-case-frontend-pr-34

#35 LAU-36: Fix Fortify Issue.
  package.json
  src/main/server.ts
  yarn.lock
Labels: ns:lau, prd:lau, rel:lau-case-frontend-pr-35

#36 LAU-184 Add loading spinners. CSV download is now handled by client
  src/main/assets/js/home.ts
  src/main/assets/scss/loading-spinner.scss
  src/main/assets/scss/main.scss
  src/main/controllers/case-activity.controller.ts
  src/main/controllers/case-searches.controller.ts
  src/main/views/case-activity/template.njk
  src/main/views/case-searches/template.njk
  src/main/views/common/template.njk
  src/test/unit/routes/caseActivity.test.ts
  src/test/unit/routes/caseSearches.test.ts
Labels: ns:lau, prd:lau, rel:lau-case-frontend-pr-36
